/**
 * Extended part catalog entries (src/lib/parts/catalog.json), generated by
 * scripts/build-catalog.ts from the LDraw library and LDCad's shadow library.
 */

export type PinKind = "wpin" | "tpin";
export type Dir = "+x" | "-x" | "+z" | "-z";

/** A wheel pin on a holder, or a wheel's hub (hole). */
export interface PinDef {
  /** "wpin" = classic wheel pin (thin); "tpin" = large pin (the pin-and-axle system's). A hub only fits pins of its kind. */
  kind: PinKind;
  /** Point on the axis where the pin leaves the body / the hub's hole opens, local units: x/z studs from the min corner, y plates from the bottom. */
  at: [number, number, number];
  /** Pins: the direction they point. Hubs: the direction the hole opens toward. */
  dir: Dir;
}

/** [cx, cz] (studs: on top, anti-studs: underneath) or [cx, cz, level] with level in plates above the part's bottom. */
export type ConnectorCell = [number, number] | [number, number, number];

export interface CatalogEntry {
  /** LDraw file name without .dat (e.g. "3823", "4624c01"). */
  id: string;
  name: string;
  cat: string;
  w: number;
  d: number;
  h: number;
  /** Omitted = a stud on every top cell. */
  studs?: ConnectorCell[];
  /** Omitted = an anti-stud under every cell at the bottom. */
  bottom?: ConnectorCell[];
  /** Filled space; omitted = the whole box. */
  solids?: [number, number, number, number, number, number][];
  pins?: PinDef[];
  hub?: PinDef;
  /** Fraction of the box that's material. */
  mass: number;
  ldraw: { file: string; yaw: 0 | 90 | 180 | 270; origin: [number, number, number] };
  /** The left/right counterpart. */
  mirror?: string;
  /** BrickLink items when they differ from the LDraw number (e.g. rim + tyre). */
  bricklink?: { id: string; color?: number }[];
  hint?: string;
  /** Anti-studs inferred from the underside geometry because the shadow library has none for this part. */
  inferred?: boolean;
  /** Has studs on its sides: a carrier for sideways building (loaded only when CONFIG.sideways.enabled). */
  snot?: boolean;
  /** Side studs: base point (x/z studs from the min corner, y plates up from the grid bottom) and outward direction. */
  sideStuds?: { at: [number, number, number]; dir: Dir }[];
  /** Body outside the grid box (a bracket's flange), boxes in LDU [x0, y0, z0, x1, y1, z1], local frame. */
  fine?: [number, number, number, number, number, number][];
}
